#!/usr/bin/env bash
# Generates all Sprout secrets.
#
# Usage (native — needs openssl + python3 + cryptography):
#   bash scripts/generate-secrets.sh
#
# Usage (Docker — no local dependencies needed):
  docker run --rm -it \
    -v "$(pwd)/tmp:/out" \
    -v "$(pwd)/scripts/generate-secrets.sh:/generate-secrets.sh:ro" \
    -e OUTPUT=/out/.env \
    python:3.12-slim \
    sh -c "apt-get install -y openssl -qq && pip install cryptography -q && bash /generate-secrets.sh"

set -euo pipefail

OUTPUT="${OUTPUT:-}"   # optional: path to write .env file, e.g. tmp/.env
K8S_OUTPUT="${K8S_OUTPUT:-}"  # optional: path to write Kubernetes secret YAML

# ── helpers ──────────────────────────────────────────────────────────────────

prompt() {
  local var="$1" label="$2" default="${3:-}"
  if [ -n "$default" ]; then
    read -rp "$label [$default]: " val
    echo "${val:-$default}"
  else
    read -rp "$label: " val
    echo "$val"
  fi
}

prompt_secret() {
  local label="$1"
  read -rsp "$label: " val; echo >&2
  echo "$val"
}

generate_vapid_keys() {
  python3 - <<'EOF'
from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.hazmat.primitives.serialization import Encoding, PublicFormat
import base64
k = ec.generate_private_key(ec.SECP256R1())
priv = base64.urlsafe_b64encode(k.private_numbers().private_value.to_bytes(32, 'big')).rstrip(b'=').decode()
pub  = base64.urlsafe_b64encode(k.public_key().public_bytes(Encoding.X962, PublicFormat.UncompressedPoint)).rstrip(b'=').decode()
print(f"{priv} {pub}")
EOF
}

# ── generated secrets ─────────────────────────────────────────────────────────

echo "Generating secrets..." >&2
echo >&2

JWT_SECRET=$(openssl rand -hex 32)

SETTINGS_ENCRYPTION_KEY=$(python3 -c "import os, base64; print(base64.urlsafe_b64encode(os.urandom(32)).decode())")

read -r VAPID_PRIVATE_KEY VAPID_PUBLIC_KEY <<< "$(generate_vapid_keys)"

# ── prompted secrets ──────────────────────────────────────────────────────────

ADMIN_EMAIL=$(prompt "ADMIN_EMAIL" "Admin email")
ADMIN_PASSWORD=$(prompt_secret "Admin password")
ADMIN_NAME=$(prompt "ADMIN_NAME" "Admin display name" "Admin")
VAPID_EMAIL=$(prompt "VAPID_EMAIL" "VAPID contact email (mailto:...)" "mailto:${ADMIN_EMAIL}")

echo >&2
echo "Optional — press Enter to skip:" >&2
ANTHROPIC_API_KEY=$(prompt "ANTHROPIC_API_KEY" "Anthropic API key (for AI care suggestions)")
OPENAI_API_KEY=$(prompt "OPENAI_API_KEY" "OpenAI API key (for AI care suggestions)")
AI_PROVIDER=$(prompt "AI_PROVIDER" "AI provider (anthropic/openai)" "anthropic")
PERENUAL_API_KEY=$(prompt "PERENUAL_API_KEY" "Perenual API key (for species search)")

# ── output ────────────────────────────────────────────────────────────────────

ENV_CONTENT="# Generated by scripts/generate-secrets.sh
JWT_SECRET=${JWT_SECRET}
SETTINGS_ENCRYPTION_KEY=${SETTINGS_ENCRYPTION_KEY}
ADMIN_EMAIL=${ADMIN_EMAIL}
ADMIN_PASSWORD=${ADMIN_PASSWORD}
ADMIN_NAME=${ADMIN_NAME}
VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY}
VAPID_PUBLIC_KEY=${VAPID_PUBLIC_KEY}
VAPID_EMAIL=${VAPID_EMAIL}
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
OPENAI_API_KEY=${OPENAI_API_KEY}
AI_PROVIDER=${AI_PROVIDER}
PERENUAL_API_KEY=${PERENUAL_API_KEY}
"

if [ -n "$OUTPUT" ]; then
  echo "$ENV_CONTENT" > "$OUTPUT"
  echo "✓ Written to $OUTPUT" >&2
else
  echo >&2
  echo "── .env ─────────────────────────────────────────" >&2
  echo "$ENV_CONTENT"
fi

# ── Kubernetes secret YAML ────────────────────────────────────────────────────

b64() { printf '%s' "$1" | base64 | tr -d '\n'; }

K8S_CONTENT="apiVersion: v1
kind: Secret
metadata:
  name: sprout-secrets
  namespace: sprout
type: Opaque
data:
  JWT_SECRET: $(b64 "$JWT_SECRET")
  SETTINGS_ENCRYPTION_KEY: $(b64 "$SETTINGS_ENCRYPTION_KEY")
  ADMIN_EMAIL: $(b64 "$ADMIN_EMAIL")
  ADMIN_PASSWORD: $(b64 "$ADMIN_PASSWORD")
  VAPID_PRIVATE_KEY: $(b64 "$VAPID_PRIVATE_KEY")
  VAPID_PUBLIC_KEY: $(b64 "$VAPID_PUBLIC_KEY")
  AI_PROVIDER: $(b64 "$AI_PROVIDER")
  ANTHROPIC_API_KEY: $(b64 "$ANTHROPIC_API_KEY")
  OPENAI_API_KEY: $(b64 "$OPENAI_API_KEY")
  PERENUAL_API_KEY: $(b64 "$PERENUAL_API_KEY")
"

if [ -n "$K8S_OUTPUT" ]; then
  echo "$K8S_CONTENT" > "$K8S_OUTPUT"
  echo "✓ Kubernetes secret written to $K8S_OUTPUT" >&2
else
  echo "── Kubernetes secret ────────────────────────────" >&2
  echo "$K8S_CONTENT"
fi
